version: '3.9'
services:
  db:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: my_backend
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: postgres
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
  
  frontend:
    build: ./frontend
    container_name: my_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: always

volumes:
  db_data:
